### ISSUE TITLE
External URL fetch in Library

### ISSUE THREAD

**Issue by haydenk** [lobstrio/shadow-useragent#7]
https://github.com/lobstrio/shadow-useragent/blob/2675d5a082234b71b719ecfb17ec864747424ef4/shadow_useragent/core.py#L14

This seems like a really useful package but I am not that thrilled about having it ping an unknown server periodically.

* How often does the "most popular user agent" *actually* change?
* Is it possible to periodically update a second library with this data that can be added as a dependency or perhaps make the application available *(perhaps OSS)* so that someone could host their own service?

**Comment by lobstrio** [comment]
@haydenk Thanks for raising, and sorry for delay. 
We are taking back maintenance of this package. 

Please find answers to your questions : 
**How often does the "most popular user agent" actually change?**

Very often. Browsers and being updated on a regular basis and the api has to reflect this. 

**Is it possible to periodically update a second library with this data that can be added as a dependency or perhaps make the application available (perhaps OSS) so that someone could host their own service?**

I can publish the api repo, which is a Django repository. If you are interested, please let me know, I'll publish the repo within 1à days. 

I'm leaving this issue open, waiting for your answer.

**Comment by lordvandal** [comment]
Unfortunately, the inevitable seems to have happened - the package stopped working a couple of hours ago, because the URL became unavailable:

`URL = "http://51.158.74.109/useragents/?format=json"`

**502 Bad Gateway
nginx/1.10.3 (Ubuntu)**

**Comment by inthevortex** [comment]
Same problem here, my scrapers stopped working suddenly. Can't we have an offline option if anyone wants to use that?

**Comment by Estaluna** [comment]
In addition, the force_update() method doesn't seem to be working considering that http://51.158.74.109/useragents/?format=json is currently available:
2020-11-22 21:08:19 [shadow-useragent] ERROR: {'last_update': datetime.datetime(2020, 11, 22, 21, 3, 25, 322867, tzinfo=<DstTzInfo 'Europe/Paris' CET+1:00:00 STD>)}
2020-11-22 21:08:19 [shadow-useragent] WARNING: Last update is 2020-11-22 21:03:25.322867+01:00, please use force_update() to force refresh

**Comment by ZoidbergPi** [comment]
Sadly, 51.158.74.109 is dead now.

**Comment by haydenk** [comment]
@lobstrio Hey, sorry it's been a few months. I had a thing pop up at work that took my attention for most of the rest of 2020.

I would definitely be interested in the API project.

**Comment by squeeb** [comment]
Why is there even a hardcoded AWS IP in this?
